### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by klazuka** [alexanderkiel/idea-haskell#1]
I was looking around for how other IntelliJ plugins have handled parsing whitespace-sensitive languages (like Haskell), and I found this project. I came for the indentation stack lexing, but I fell in love with your parsing rule DSL and PsiBuilder helpers 😄 

But then I couldn't find a license or copyright on the code? If it's not too presumptuous to ask, would you consider adding an open-source license? More details on unlicensed code [here](https://choosealicense.com/no-license/).

Thanks for your consideration 🙏

**Comment by alexanderkiel** [comment]
@klazuka: thanks for asking. I added an Eclipse Public License. Is that sufficient for you?

**Comment by klazuka** [comment]
@alexanderkiel great, thanks!
